on:
  release:
    types: [published]

name: Publish to nuget.org

# Note that the VERSION_STATIC is set to 0.0.0.0. This is so that the action uses the version of Nerdversioning as well as always pushes a new package to nuget.org         
jobs:
  build:
    name: Push packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1        
        with:
          dotnet-version: 5.0.x        
      - name: Publish MLOps.NET
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/MLOps.NET/MLOps.NET.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
          VERSION_STATIC: 0.0.0   
          TAG_COMMIT: false    
      - name: Publish MLOps.NET.AWS             
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/MLOps.NET.AWS/MLOps.NET.AWS.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}  
          VERSION_STATIC: 0.0.0   
          TAG_COMMIT: false       
      - name: Publish MLOps.NET.Azure          
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/MLOps.NET.Azure/MLOps.NET.Azure.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: 0.0.0      
          TAG_COMMIT: false  
      - name: Publish MLOps.NET.SQLite          
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/MLOps.NET.SQLite/MLOps.NET.SQLite.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}  
          VERSION_STATIC: 0.0.0   
          TAG_COMMIT: false        
      - name: Publish MLOps.NET.SQLServer          
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/MLOps.NET.SQLServer/MLOps.NET.SQLServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
          VERSION_STATIC: 0.0.0       
          TAG_COMMIT: false    
      - name: Publish MLOps.NET.CLI          
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/MLOps.NET.CLI/MLOps.NET.CLI.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}    
          VERSION_STATIC: 0.0.0    
          TAG_COMMIT: false           
                                                                         
